<?php

namespace Database\Seeders;

use App\Models\Dosen;
use App\Models\DosenHomebase;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DosenMatematikaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $dosens = [
            [
                'nidn' => '0025086706',
                'nama' => 'AGUS INDRA JAYA',
                'kelamin' => 0,
                'pendidikan' => 2,
                'golongan' => 'IV/a',
                'fungsional' => 3,
                'upload' => null,
                'homebase' => 44201,
                'perusahaan_industri' => null,
                'bidang_keahlian' => 'Matematika',
                'kesesuaian_kompetensi' => 1,
                'pendidikan_magister' => 'University of Twente',
                'pendidikan_doctoral' => null,
                'nomor_sertifikasi' => null,
                'nomor_sertifikasi_profesi_industri' => null,
                'matakuliah_prodi' => 'Matematika',
                'kesesuaian_matakuliah' => 1,
                'matakuliah_prodi_lain' => 'Matematika Dasar',
            ],
            [
                'nidn' => '0011086608',
                'nama' => 'RINA RATIANINGSIH',
                'kelamin' => 1,
                'pendidikan' => 2,
                'golongan' => 'IV/a',
                'fungsional' => 3,
                'upload' => null,
                'homebase' => 44201,
                'perusahaan_industri' => null,
                'bidang_keahlian' => 'Matematika',
                'kesesuaian_kompetensi' => 1,
                'pendidikan_magister' => null,
                'pendidikan_doctoral' => 'Institut Teknologi Bandung',
                'nomor_sertifikasi' => null,
                'nomor_sertifikasi_profesi_industri' => null,
                'matakuliah_prodi' => 'Matematika',
                'kesesuaian_matakuliah' => 1,
                'matakuliah_prodi_lain' => 'Matematika Dasar',
            ],
            [
                'nidn' => '0001037304',
                'nama' => 'SELVY MUSDALIFAH',
                'kelamin' => 1,
                'pendidikan' => 2,
                'golongan' => 'IV/a',
                'fungsional' => 3,
                'upload' => null,
                'homebase' => 44201,
                'perusahaan_industri' => null,
                'bidang_keahlian' => 'Matematika',
                'kesesuaian_kompetensi' => 1,
                'pendidikan_magister' => 'Institut Teknologi Bandung',
                'pendidikan_doctoral' => null,
                'nomor_sertifikasi' => null,
                'nomor_sertifikasi_profesi_industri' => null,
                'matakuliah_prodi' => 'Matematika',
                'kesesuaian_matakuliah' => 1,
                'matakuliah_prodi_lain' => 'Matematika Dasar',
            ],
            [
                'nidn' => '0020067205',
                'nama' => 'I WAYAN SUDARSANA',
                'kelamin' => 0,
                'pendidikan' => 3,
                'golongan' => 'IV/a',
                'fungsional' => 5,
                'upload' => null,
                'homebase' => 44201,
                'perusahaan_industri' => null,
                'bidang_keahlian' => 'Kombinatorika',
                'kesesuaian_kompetensi' => 1,
                'pendidikan_magister' => 'Institut Teknologi Bandung',
                'pendidikan_doctoral' => 'Institut Teknologi Bandung',
                'nomor_sertifikasi' => null,
                'nomor_sertifikasi_profesi_industri' => null,
                'matakuliah_prodi' => 'Matematika',
                'kesesuaian_matakuliah' => 1,
                'matakuliah_prodi_lain' => 'Matematika Dasar',
            ],
            [
                'nidn' => '0027017903',
                'nama' => 'AGUSMAN SAHARI',
                'kelamin' => 0,
                'pendidikan' => 2,
                'golongan' => 'IV/a',
                'fungsional' => 2,
                'upload' => null,
                'homebase' => 44201,
                'perusahaan_industri' => null,
                'bidang_keahlian' => 'ROPD',
                'kesesuaian_kompetensi' => 1,
                'pendidikan_magister' => 'Universitas Hasanuddin',
                'pendidikan_doctoral' => null,
                'nomor_sertifikasi' => null,
                'nomor_sertifikasi_profesi_industri' => null,
                'matakuliah_prodi' => 'Matematika',
                'kesesuaian_matakuliah' => 1,
                'matakuliah_prodi_lain' => 'Matematika Dasar',
            ],
            [
                'nidn' => '0007058203',
                'nama' => 'RESNAWATI',
                'kelamin' => 1,
                'pendidikan' => 2,
                'golongan' => 'IV/a',
                'fungsional' => 2,
                'upload' => null,
                'homebase' => 44201,
                'perusahaan_industri' => null,
                'bidang_keahlian' => 'Aljabar Analisis',
                'kesesuaian_kompetensi' => 1,
                'pendidikan_magister' => 'Universitas Hasanuddin',
                'pendidikan_doctoral' => null,
                'nomor_sertifikasi' => null,
                'nomor_sertifikasi_profesi_industri' => null,
                'matakuliah_prodi' => 'Matematika',
                'kesesuaian_matakuliah' => 1,
                'matakuliah_prodi_lain' => 'Matematika Dasar',
            ],
            [
                'nidn' => '0026069002',
                'nama' => 'JUNI WIJAYANTI PUSPITA',
                'kelamin' => 1,
                'pendidikan' => 3,
                'golongan' => 'IV/a',
                'fungsional' => 1,
                'upload' => null,
                'homebase' => 44201,
                'perusahaan_industri' => null,
                'bidang_keahlian' => 'Terapan',
                'kesesuaian_kompetensi' => 1,
                'pendidikan_magister' => 'Institut Teknologi Bandung',
                'pendidikan_doctoral' => 'Institut Teknologi Bandung',
                'nomor_sertifikasi' => null,
                'nomor_sertifikasi_profesi_industri' => null,
                'matakuliah_prodi' => 'Matematika',
                'kesesuaian_matakuliah' => 1,
                'matakuliah_prodi_lain' => 'Matematika Dasar',
            ],
            [
                'nidn' => '0028128802',
                'nama' => 'DESI LUSIYANTI',
                'kelamin' => 1,
                'pendidikan' => 2,
                'golongan' => 'IV/a',
                'fungsional' => 2,
                'upload' => null,
                'homebase' => 44201,
                'perusahaan_industri' => null,
                'bidang_keahlian' => 'Komputasi',
                'kesesuaian_kompetensi' => 1,
                'pendidikan_magister' => 'Institut Teknologi Sepuluh November',
                'pendidikan_doctoral' => null,
                'nomor_sertifikasi' => null,
                'nomor_sertifikasi_profesi_industri' => null,
                'matakuliah_prodi' => 'Matematika',
                'kesesuaian_matakuliah' => 1,
                'matakuliah_prodi_lain' => 'Matematika Dasar',
            ],
            [
                'nidn' => '0020049002',
                'nama' => 'HAJAR',
                'kelamin' => 1,
                'pendidikan' => 2,
                'golongan' => 'IV/a',
                'fungsional' => 1,
                'upload' => null,
                'homebase' => 44201,
                'perusahaan_industri' => null,
                'bidang_keahlian' => 'Terapan',
                'kesesuaian_kompetensi' => 1,
                'pendidikan_magister' => 'Institut Teknologi Sepuluh November',
                'pendidikan_doctoral' => null,
                'nomor_sertifikasi' => null,
                'nomor_sertifikasi_profesi_industri' => null,
                'matakuliah_prodi' => 'Matematika',
                'kesesuaian_matakuliah' => 1,
                'matakuliah_prodi_lain' => 'Matematika Dasar',
            ],
            [
                'nidn' => '0005078904',
                'nama' => 'NASRIA NACONG',
                'kelamin' => 1,
                'pendidikan' => 2,
                'golongan' => 'IV/a',
                'fungsional' => 1,
                'upload' => null,
                'homebase' => 44201,
                'perusahaan_industri' => null,
                'bidang_keahlian' => 'Terapan',
                'kesesuaian_kompetensi' => 1,
                'pendidikan_magister' => 'Institut Teknologi Sepuluh November',
                'pendidikan_doctoral' => null,
                'nomor_sertifikasi' => null,
                'nomor_sertifikasi_profesi_industri' => null,
                'matakuliah_prodi' => 'Matematika',
                'kesesuaian_matakuliah' => 1,
                'matakuliah_prodi_lain' => 'Matematika Dasar',
            ],
            [
                'nidn' => '0029049004',
                'nama' => 'ANDRI',
                'kelamin' => 0,
                'pendidikan' => 2,
                'golongan' => 'IV/a',
                'fungsional' => 2,
                'upload' => null,
                'homebase' => 44201,
                'perusahaan_industri' => null,
                'bidang_keahlian' => 'Aljabar',
                'kesesuaian_kompetensi' => 1,
                'pendidikan_magister' => 'Universitas Gadjah Mada',
                'pendidikan_doctoral' => null,
                'nomor_sertifikasi' => null,
                'nomor_sertifikasi_profesi_industri' => null,
                'matakuliah_prodi' => 'Matematika',
                'kesesuaian_matakuliah' => 1,
                'matakuliah_prodi_lain' => 'Matematika Dasar',
            ],
            [
                'nidn' => '0007099201',
                'nama' => 'MAULIDYANU ABU',
                'kelamin' => 1,
                'pendidikan' => 2,
                'golongan' => 'IV/a',
                'fungsional' => 1,
                'upload' => null,
                'homebase' => 44201,
                'perusahaan_industri' => null,
                'bidang_keahlian' => 'Terapan',
                'kesesuaian_kompetensi' => 1,
                'pendidikan_magister' => 'Institut Teknologi Sepuluh November',
                'pendidikan_doctoral' => null,
                'nomor_sertifikasi' => null,
                'nomor_sertifikasi_profesi_industri' => null,
                'matakuliah_prodi' => 'Matematika',
                'kesesuaian_matakuliah' => 1,
                'matakuliah_prodi_lain' => 'Matematika Dasar',
            ],
            [
                'nidn' => '0029049201',
                'nama' => 'ABDUL MAHATIR NAJAR',
                'kelamin' => 1,
                'pendidikan' => 2,
                'golongan' => 'IV/a',
                'fungsional' => 1,
                'upload' => null,
                'homebase' => 44201,
                'perusahaan_industri' => null,
                'bidang_keahlian' => 'Komputasi',
                'kesesuaian_kompetensi' => 1,
                'pendidikan_magister' => 'Institut Teknologi Sepuluh November',
                'pendidikan_doctoral' => null,
                'nomor_sertifikasi' => null,
                'nomor_sertifikasi_profesi_industri' => null,
                'matakuliah_prodi' => 'Matematika',
                'kesesuaian_matakuliah' => 1,
                'matakuliah_prodi_lain' => 'Matematika Dasar',
            ],
            [
                'nidn' => '0001119110',
                'nama' => 'IMAN AL FAJRI',
                'kelamin' => 1,
                'pendidikan' => 2,
                'golongan' => 'IV/a',
                'fungsional' => 1,
                'upload' => null,
                'homebase' => 44201,
                'perusahaan_industri' => null,
                'bidang_keahlian' => 'Terapan',
                'kesesuaian_kompetensi' => 1,
                'pendidikan_magister' => 'Universitas Hasanuddin',
                'pendidikan_doctoral' => null,
                'nomor_sertifikasi' => null,
                'nomor_sertifikasi_profesi_industri' => null,
                'matakuliah_prodi' => 'Matematika',
                'kesesuaian_matakuliah' => 1,
                'matakuliah_prodi_lain' => 'Matematika Dasar',
            ],
        ];

        foreach ($dosens as $d) {

            DB::transaction(function () use ($d){
                DosenHomebase::create($d);
            });
        }
    }
}
